#!/usr/bin/with-contenv sh

echo "$GUAC_VER" > /config/.database-version

/etc/cont-init.d/30-defaults.sh
/etc/cont-init.d/40-database.sh
/etc/cont-init.d/50-extensions

echo "Starting guacamole client..."
s6-setuidgid root catalina.sh run
