#!/usr/bin/with-contenv sh

echo "$GUAC_VER" > /config/.database-version

if [ "$(grep postgresql-hostname /config/guacamole/guacamole.properties | wc -l)" -eq 0 ]; then
  echo "postgresql-hostname: $POSTGRES_HOST" >> /config/guacamole/guacamole.properties
fi

if [ "$(grep postgresql-hostname /config/guacamole/guacamole.properties | wc -l)" -eq 0 ]; then
  echo "postgresql-port: $POSTGRES_PORT" >> /config/guacamole/guacamole.properties
fi

if [ "$(grep postgresql-hostname /config/guacamole/guacamole.properties | wc -l)" -eq 0 ]; then
  echo "postgresql-database: $POSTGRES_DATABASE" >> /config/guacamole/guacamole.properties
fi

if [ "$(grep postgresql-hostname /config/guacamole/guacamole.properties | wc -l)" -eq 0 ]; then
  echo "postgresql-username: $POSTGRES_USER" >> /config/guacamole/guacamole.properties
fi

if [ "$(grep postgresql-hostname /config/guacamole/guacamole.properties | wc -l)" -eq 0 ]; then
  echo "postgresql-password: $POSTGRES_PASS" >> /config/guacamole/guacamole.properties
fi

/etc/cont-init.d/30-defaults.sh
/etc/cont-init.d/50-extensions

echo "Starting guacamole client..."
s6-setuidgid root catalina.sh run
